// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using HotChocolate;
namespace SMMS.GraphQLClients.BlazorWAS.NghiaHT.Models;


public partial class RequestNghiaHt
{
    [GraphQLIgnore]
    public int RequestNghiaHtid { get; set; }

    [Required]
    public int? MedicationCategoryQuanTnid { get; set; }

    [Required]
    public string MedicationName { get; set; }

    [Required]
    public string Dosage { get; set; }

    [Required]
    public string Frequency { get; set; }

    [Required]
    public string Reason { get; set; }

    [Required]
    public string Instruction { get; set; }

    public string Form { get; set; }

    [Required]
    public int? Quantity { get; set; }

    public string Strength { get; set; }

    public string Indications { get; set; }

    public string Contraindications { get; set; }

    [Required]
    public DateTime? CreatedDate { get; set; }

    [Required]
    public DateTime? StartDate { get; set; }
    
    public bool IsApproved { get; set; }

    public virtual MedicationCategoryQuanTn MedicationCategoryQuanTn { get; set; }
}

public partial class RequestNghiaHtsGraphQLResponse
{
    public List<RequestNghiaHt> requestNghiaHt { get; set; }
}

public partial class RequestNghiaHtGraphQLResponse
{
    public RequestNghiaHt requestNghiaHtById { get; set; }
}

public class CreateRequestNghiaHtResponse
{
    public int createRequestNghiaHt { get; set; }
}

public class DeleteRequestNghiaHtResponse
{
    public bool deleteRequestNghiaHt { get; set; }
}

public class UpdateRequestNghiaHtResponse { public int updateRequestNghiaHt { get; set; } }

//public class UpdateRequestNghiaHtData { public int requestNghiaHtid { get; set; } }