// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using HotChocolate;
namespace SMMS.GraphQLClients.BlazorWAS.NghiaHT.Models;


public partial class RequestNghiaHt
{
    [GraphQLIgnore]
    public int RequestNghiaHtid { get; set; }

    public int? MedicationCategoryQuanTnid { get; set; }

    public string MedicationName { get; set; }

    public string Dosage { get; set; }

    public string Frequency { get; set; }

    public string Reason { get; set; }

    public string Instruction { get; set; }

    public string Form { get; set; }

    public int? Quantity { get; set; }

    public string Strength { get; set; }

    public string Indications { get; set; }

    public string Contraindications { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? StartDate { get; set; }

    //public bool? IsApproved { get; set; }
    public bool IsApproved { get; set; }

    public virtual MedicationCategoryQuanTn MedicationCategoryQuanTn { get; set; }
}

public partial class RequestNghiaHtsGraphQLResponse
{
    public List<RequestNghiaHt> requestNghiaHt { get; set; }
}

public partial class RequestNghiaHtGraphQLResponse
{
    public RequestNghiaHt requestNghiaHt { get; set; }
}

public class CreateRequestNghiaHtResponse
{
    public int createRequestNghiaHt { get; set; }
}